openapi: "3.1.0"
info:
  title: "payment_system API"
  description: "payment_system API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080"
paths:
  /api/v1/payments:
    post:
      summary: "POST api/v1/payments"
      operationId: "processPayment"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PaymentDTO"
    get:
      summary: "GET api/v1/payments"
      operationId: "getPayments"
      parameters:
        - name: "senderId"
          in: "query"
          required: false
          schema:
            type: "string"
            format: "uuid"
        - name: "receiverId"
          in: "query"
          required: false
          schema:
            type: "string"
            format: "uuid"
        - name: "page"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int32"
            default: "0"
        - name: "pageSize"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int32"
            default: "20"
        - name: "startDate"
          in: "query"
          required: false
          schema:
            type: "string"
            format: "date-time"
        - name: "endDate"
          in: "query"
          required: false
          schema:
            type: "string"
            format: "date-time"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PaymentDTO"
  /api/v1/payments/{paymentId}:
    get:
      summary: "GET api/v1/payments/{paymentId}"
      operationId: "getPaymentByPaymentId"
      parameters:
        - name: "paymentId"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PaymentDTO"
components:
  schemas:
    BigDecimal:
      type: "number"
    PaymentRequest:
      type: "object"
      properties:
        amount:
          $ref: "#/components/schemas/BigDecimal"
        senderUserId:
          type: "string"
          format: "uuid"
        receiverUserId:
          type: "string"
          format: "uuid"
    PaymentDTO:
      type: "object"
      properties:
        paymentId:
          type: "string"
          format: "uuid"
        senderId:
          type: "string"
          format: "uuid"
        receiverId:
          type: "string"
          format: "uuid"
        amount:
          $ref: "#/components/schemas/BigDecimal"
        timestamp:
          type: "string"
          format: "date-time"